name: CI

on:
  push:
    branches:
      - 'main'
  pull_request:
    branches:
      - 'main'
  schedule:
    - cron: '0 0 * * 1'

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  static:
    name: Static Analysis
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: json, mbstring, curl
          coverage: none

      - name: Install dependencies
        run: composer install --prefer-dist --no-progress --no-interaction

      - name: Run PHP_CodeSniffer
        run: composer phpcs

      - name: Run PHPStan
        run: composer phpstan

      - name: Run Psalm
        run: composer psalm

  test:
    uses: dvsa/.github/.github/workflows/php-tests.yml@v4.1.0
    with:
      php-versions: "[\"8.2\"]"
      composer-version: '2.2.24'

  security:
    uses: dvsa/.github/.github/workflows/php-security.yml@v4.1.0
    with:
      php-version: "8.2"
    secrets:
      SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
